NumPy is the fundamental package for scientific computing with Python. It contains among other things:

- 功能强大的N维数组对象。
- 精密广播功能函数。
- 集成 C/C+和Fortran 代码的工具。
- 强大的线性代数、傅立叶变换和随机数功能

In [2]:
import numpy as np

### 数组的生成/创建

In [3]:

print(np.random.permutation(10))  # 如果传入一个整数，它会返回一个洗牌后的arange

a = [0,1,2,3,4,5]
print(np.random.permutation(a))
a = [0,1,2,3,4,5]
print(np.random.shuffle(a))
print(a)

[8 1 2 3 7 5 6 4 0 9]
[0 1 5 3 4 2]
None
[0, 4, 1, 5, 3, 2]


In [ ]:
np.random.randn(300).shape   # 生成300-dim的随机向量

In [ ]:
np.zeros(300).shape # 生成300-dim的领向量

In [ ]:
ars = np.arange(0,100000,1)
# ars

In [ ]:
np.int8(12.334)

In [ ]:
np.bool([1,2,0])

In [ ]:
# 创建三维数组 arange的长度与ndarray的维度的乘积要相等，即 24 = 2X3X4
arr = np.arange(24).reshape(2,3,4)
arr

In [404]:
np.linspace(0,np.pi,3) #  start,end,number_element

array([0.        , 1.57079633, 3.14159265])

In [ ]:
def f(x,y):   #  x=i, y=j
    return 10*x+y
df = np.fromfunction(f,(5,4),dtype=int)
df

In [372]:
cc = np.random.choice(10, 3)
cc

array([1, 2, 9])

In [380]:
import random 
random.choice(cc)

2

In [379]:
import random 
random.sample(list(cc), 2)

[2, 9]

##### 数据的保存和加载

In [ ]:
d_data = {"121":"1212121"}
np.savez_compressed("./data/compressed_data.npz", d_data=d_data)

In [ ]:
data = np.load("./data/compressed_data.npz", allow_pickle=True)
print(data["d_data"])

### 数组ops

In [403]:
# clip这个函数将将数组中的元素限制在a_min, a_max之间，大于a_max的就使得它等于 a_max，小于a_min,的就使得它等于a_min。
import numpy as np
x=np.array([1,2,3,5,6,7,8,9])
np.clip(x,3,8)

array([3, 3, 3, 5, 6, 7, 8, 8])

In [400]:
numpy.fabs([1,-1])

array([1., 1.])

In [ ]:
# 删掉为1的维度
A = np.array([[[0], [1], [2]]])
A = np.squeeze(A)
A

##### 转置 transpose

In [390]:
a = np.array([3, 1, 2])
b = np.array([4, 6, 2])
b.shape

(3,)

In [392]:
br = b.reshape(b.shape[0],1) #  一维数组的转置
br.shape

(3, 1)

In [ ]:
b.reshape(b.shape[0],1) * a 

In [ ]:
b = np.arange(24).reshape(4,6)
b

In [ ]:
b.T

##### 复数

In [ ]:
d = np.array([1.2+2j, 2+3j])
d

In [ ]:
d.real

In [ ]:
d.imag

##### flat属性，返回一个numpy.flatiter对象，即可迭代的对象。

In [ ]:
e = np.arange(6).reshape(2,3)
e
f = e.flat
print(f[2])
for item in f:
    print(item)

#### 筛选/filter/map/reduce

In [ ]:
a =  np.arange(7)
a[1:4] 

In [ ]:
# 每间隔2个取一个数
a[ : 6: 2]

In [ ]:
u = np.array([1,2,4,5,1,2,3])
np.unique(u)

In [ ]:
np.ptp(u)#数组沿指定轴返回最大值减去最小值，即（max-min）

In [ ]:
np.var(u) #返回方差（variance）

In [ ]:
np.cumprod(u) #返回累乘积值

In [ ]:
np.cumsum(u)  # 返回累加值

In [ ]:
np.argmax(a,axis=1)  # axis=1 按行，找最大值

In [ ]:
np.argmin(a) # 找整个矩阵的最小值

In [ ]:
d = [1,2,3,4,5,10]
np.where(d==np.max(d)) # numpy array数组的最值及其索引

In [ ]:
# 关联筛选
xs = np.array([0,1,2,2,5]).astype("float64")  # 创建ndarray数组时，可以指定数值类型
vs = np.array([-1,1,1,-1,1]).astype("float64")
ws = np.array([0,1,2,3,0]).astype("float64")

vd = np.diff(vs)
print(vd)
# np.where(vd==np.min(vd))[0]
xd = np.diff(xs)
print(xd)
# gap_xd = np.where(vd==-2)
# print(gap_xd)
xd = np.min(xd[np.where(vd==-2)[0]])
xd = xd[xd>0]
if len(xd)>0:
    min_gap = np.min(xd)
min_gap

In [ ]:
a = np.array([])
b = np.array([1,2,3])
b[np.where(a>0)]

In [ ]:
sum(ws)

In [ ]:
xs += vs*(min_gap/2)
xs

In [ ]:
ws[np.where(xs<0)]  #  条件筛选 下标/元素

In [ ]:
di = np.diff(xs)  # 计算数组的相邻元素之间的差异
poses = np.where(di==np.min(di))[0]
# for p in poses:
#     print(p[0])
cvs = np.ones(5)
for p in poses:
    cvs[p] = -1
    cvs[p+1] = -1
cvs

In [ ]:
# update vs
vs = vs * cvs
vs

In [ ]:
np.argmax(a,axis=0)

##### where sql

In [47]:
# 找下标
y_train = np.array([1,1,2,3,4,5,6,7,8,9])
indexes = np.where(y_train==1)[0]
indexes

array([0, 1])

In [48]:
indexes

array([0, 1])

In [53]:
np.where(y_train>4,"gt4","lt4")  # replace

array(['lt4', 'lt4', 'lt4', 'lt4', 'lt4', 'gt4', 'gt4', 'gt4', 'gt4',
       'gt4'], dtype='<U3')

In [ ]:
digit_indices = [np.where(y_train == i)[0] for i in range(10)]
digit_indices

In [ ]:
# vec = np.zeros(300)
vec = np.random.randn(300)
if np.where(vec!=0)[0].shape[0]==0:
    print("---")

In [ ]:
np.where(vec!=0)[0].shape[0]

### 处理数组形状

##### reshape vs resize
函数resize（）的作用跟reshape（）类似，但是会改变所作用的数组，相当于有inplace=True的效果

In [ ]:
b = np.arange(12).reshape(3,4)
b

In [ ]:
b.reshape(4,3)

In [ ]:
b

##### ravel()和flatten()，将多维数组转换成一维数组
两者的区别在于返回拷贝（copy）还是返回视图（view）

flatten()返回一份拷贝，需要分配新的内存空间，对拷贝所做的修改不会影响原始矩阵，

ravel()返回的是视图（view），会影响原始矩阵。

In [ ]:
b

In [ ]:
bb = b.flatten()
bb[2] = 20
bb

In [ ]:
b

In [ ]:
bb = b.ravel()
bb[2] = 20
bb

In [ ]:
b

In [ ]:
# 用tuple指定数组的形状
b.shape=(6,2)
b

#### 复制

In [ ]:
# d = np.array([[1,2,3],[4,5,6]])
c = a.view() # 视图(view)和浅复制
d = a.copy() #  深复制

### 两个数组的运算

#### 堆叠数组

##### 水平叠加

In [31]:
b = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
c = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
b.shape

(3, 4)

In [ ]:
np.hstack((b,c))

In [ ]:
np.column_stack((b,c))

##### 垂直叠加

In [ ]:
np.vstack((b,c))

In [ ]:
np.row_stack((b,c))

##### concatenate

In [ ]:
np.concatenate((b,c),axis=1) # 行

In [ ]:
np.concatenate((b,c),axis=0) # 列

##### 深度叠加

In [ ]:
np.dstack((b,c)).shape  # 3,4

#### intersection

In [43]:
a = np.array([3, 1, 2])
b = np.array([4, 6, 2])
np.intersect1d(a,b)

array([2])

In [36]:
bb = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
cc = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,13]])
np.intersect1d(bb,cc)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

### allclose

In [46]:
# provide you with a great way of checking if two arrays are similar,
#  absolute(`a` - `b`) <= (`atol` + `rtol` * absolute(`b`))
np.allclose(a,b,0.8)

False

In [ ]:
b