In [5]:
from keras import backend as K
import tensorflow as tf
import numpy as np

Using TensorFlow backend.
/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/dtypes.py:519: FutureWarn

##### 欧式距离

In [58]:
def euclidean_distance(vects):
    """欧式距离"""
    x, y = vects
    return K.sqrt(K.maximum(K.sum(K.square(x - y), axis=1, keepdims=True), K.epsilon()))

In [95]:
import numpy as np
x1 = np.array([[1,2,3]]).astype("float64")
x2 = np.array([[1,3,5]]).astype("float64")
print(x1.shape)
# K.eval(K.sum(K.square(x1.reshape(1,x1.shape[0]) - x2.reshape(1,x2.shape[0])),axis=1, keepdims=True))
# K.eval(K.sum(K.square(x1 - x2),axis=1, keepdims=True))
%time K.eval(euclidean_distance((x1,x2)))

(1, 3)
CPU times: user 36 ms, sys: 0 ns, total: 36 ms
Wall time: 36.5 ms


array([[2.23606798]])

In [98]:
x1.shape

(1, 3)

In [96]:
from sklearn.metrics.pairwise import euclidean_distances
%time euclidean_distances(x1,x2)

CPU times: user 0 ns, sys: 0 ns, total: 0 ns
Wall time: 413 µs


array([[2.23606798]])

In [30]:
K.epsilon()

1e-07

##### cosine

In [81]:
def cos_distance(vects):
    x, y = vects
    fz = K.batch_dot(x,y,axes=1)
    fm1 = K.sum(K.square(x), axis=1, keepdims=True)
    fm2 = K.sum(K.square(y), axis=1, keepdims=True)
    fm = K.sqrt(fm1*fm2)
    return fz/K.maximum(fm, K.epsilon())

In [102]:
# x1 = tf.constant([[1.0,2.0]])
# x2 = tf.constant([[-2.0,-1.0]])
# print(x1.shape)
# K.eval(cos_distance((x1,x2)))

(1, 2)


array([[-0.8]], dtype=float32)

In [103]:
from sklearn.metrics.pairwise import cosine_similarity
# x1 = np.mat(np.array([1.0,2.0]).astype("float64"))
# x2 = np.mat(np.array([2.0,1.0]).astype("float64"))
# cosine_similarity(x1,x2)

http://blog.csdn.net/guojingjuan/article/details/50396254

In [1]:
from numpy import *

In [2]:
def manhattan(vector1,vector2):
    """
    曼哈顿距离
    :param vector1:
    :param vector2:
    :return:
    """
    return sum(abs(vector1 - vector2))

In [3]:
def hamming(vector1,vector2):
    """
    汉明距离
    :param vector1:
    :param vector2:
    :return:
    """
    # vector_list = vector1.tolist()[0]  # mat 转list
    vectors = [vector1.tolist()[0],vector2.tolist()[0]]  # 防止浅copy
    matV = mat(vectors)
    smstr = nonzero(matV[0] - matV[1]);
    return shape(smstr[0])[0]
#     print (matV)

In [4]:
hamming(mat([1, 1, 0, 1, 0, 1, 0, 0, 1]),mat([0, 1, 1, 0, 0, 0, 1, 1, 1]))

6

In [7]:
matV = mat([[1, 1, 0, 1, 0, 1, 0, 0, 1], [0, 1, 1, 0, 0, 0, 1, 1, 1]])
smstr = nonzero(matV[0] - matV[1])
# shape(smstr)
smstr

(array([0, 0, 0, 0, 0, 0]), array([0, 2, 3, 5, 6, 7]))